- name: Typst
  tags:
    - typst
  block:
    - name: Install (terra repository)
      ansible.builtin.dnf:
        name:
          - typst        # Requires terra repository
        state: present
      become: true

