- name: Asciidoc
  tags:
    - asciidoc
    - asciidoctor
  block:
    - name: Install asciidoctor
      ansible.builtin.dnf:
        name:
          - rubygem-asciidoctor
          - rubygem-asciidoctor-pdf
          - rubygem-rouge
        state: present
      become: true
