---
nerd_fonts: []
  # - NerdFontsSymbolsOnly
  # - Hack
  # - SourceCodePro
  # - JetBrainsMono
  # - Ubuntu
  # - UbuntuMono
  # - IntelOneMono
  # - IBMPlexMono
  # - GeistMono
  # - Monaspace     # https://monaspace.githubnext.com, https://github.com/githubnext/monaspace
  # - CascadiaCode
  # - LiberationMono
  # - Meslo
  # - FiraCode

