---

- name: Pdf Tools
  tags:
    - pdftools
    - pdf-tools
  block:
    - name: Install
      ansible.builtin.dnf:
        name:
          - pdfgrep
          - tesseract
          - tesseract-langpack-ita
          - ocrmypdf
        state: present
      become: true
