---
- name: Install
  ansible.builtin.dnf:
    name:
      - blueman # A full featured Graphical Bluetooth Manager
      - bluez-tools # Set of tools to manage Bluetooth devices for linux
      - solaar # Solaar is a Linux device manager for Logitech's Unifying Receiver wireless peripherals.
    state: present
  become: true
  tags:
    - apt
    - bluetooth
