---
- name: Bitwarden
  tags:
    - never
    - bitwarden
    - bitwarden-cli
  block:
    - name: Install bitwarden desktop
      community.general.flatpak:
        name: com.bitwarden.desktop
        state: present
        remote: flathub
