---
- name: Markdown
  tags:
    - markdown
    - markdown-utils
  block:
    - name: Install
      ansible.builtin.dnf:
        name:
          - glow
        state: present
      become: true

    - name: Install frogmouth
      ansible.builtin.pip:
        name:
          - frogmouth # A Markdown browser for your terminal: https://github.com/Textualize/frogmouth
        state: latest

